var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(b){var f=0;return function(){return f<b.length?{done:!1,value:b[f++]}:{done:!0}}};$jscomp.arrayIterator=function(b){return{next:$jscomp.arrayIteratorImpl(b)}};$jscomp.makeIterator=function(b){var f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];return f?f.call(b):$jscomp.arrayIterator(b)};
$jscomp.findInternal=function(b,f,g){b instanceof String&&(b=String(b));for(var h=b.length,p=0;p<h;p++){var m=b[p];if(f.call(g,m,p,b))return{i:p,v:m}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,f,g){b!=Array.prototype&&b!=Object.prototype&&(b[f]=g.value)};
$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(b,f,g,h){if(f){g=$jscomp.global;b=b.split(".");for(h=0;h<b.length-1;h++){var p=b[h];p in g||(g[p]={});g=g[p]}b=b[b.length-1];h=g[b];f=f(h);f!=h&&null!=f&&$jscomp.defineProperty(g,b,{configurable:!0,writable:!0,value:f})}};
$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,g){return $jscomp.findInternal(this,b,g).v}},"es6","es3");$jscomp.owns=function(b,f){return Object.prototype.hasOwnProperty.call(b,f)};$jscomp.polyfill("Object.entries",function(b){return b?b:function(b){var f=[],h;for(h in b)$jscomp.owns(b,h)&&f.push([h,b[h]]);return f}},"es8","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.SymbolClass=function(b,f){this.$jscomp$symbol$id_=b;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:f})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};
$jscomp.Symbol=function(){function b(g){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(g||"")+"_"+f++,g)}var f=0;return b}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.iterator;b||(b=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[b]&&$jscomp.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.asyncIterator;b||(b=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(b){$jscomp.initSymbolIterator();b={next:b};b[$jscomp.global.Symbol.iterator]=function(){return this};return b};
$jscomp.iteratorFromArray=function(b,f){$jscomp.initSymbolIterator();b instanceof String&&(b+="");var g=0,h={next:function(){if(g<b.length){var p=g++;return{value:f(p,b[p]),done:!1}}h.next=function(){return{done:!0,value:void 0}};return h.next()}};h[Symbol.iterator]=function(){return h};return h};$jscomp.polyfill("Array.prototype.entries",function(b){return b?b:function(){return $jscomp.iteratorFromArray(this,function(b,g){return[b,g]})}},"es6","es3");
$jscomp.polyfill("Array.from",function(b){return b?b:function(b,g,h){g=null!=g?g:function(b){return b};var f=[],m="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof m){b=m.call(b);for(var r=0;!(m=b.next()).done;)f.push(g.call(h,m.value,r++))}else for(m=b.length,r=0;r<m;r++)f.push(g.call(h,b[r],r));return f}},"es6","es3");$jscomp.polyfill("Object.is",function(b){return b?b:function(b,g){return b===g?0!==b||1/b===1/g:b!==b&&g!==g}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(b){return b?b:function(b,g){var f=this;f instanceof String&&(f=String(f));var p=f.length;g=g||0;for(0>g&&(g=Math.max(g+p,0));g<p;g++){var m=f[g];if(m===b||Object.is(m,b))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(b,f,g){if(null==b)throw new TypeError("The 'this' value for String.prototype."+g+" must not be null or undefined");if(f instanceof RegExp)throw new TypeError("First argument to String.prototype."+g+" must not be a regular expression");return b+""};$jscomp.polyfill("String.prototype.includes",function(b){return b?b:function(b,g){return-1!==$jscomp.checkStringArgs(this,b,"includes").indexOf(b,g||0)}},"es6","es3");
var $j=jQuery.noConflict(),baseto="body",basefrom="body",picArrCanvas=[];function replaceAt(b,f,g,h){return b.substr(0,f)+h+b.substr(f+g.length+1)}function textToClipboard(b){var f=document.createElement("input");document.body.appendChild(f);f.setAttribute("id","dummy_id");document.getElementById("dummy_id").value=b;f.select();f.setSelectionRange(0,99999);document.execCommand("copy");document.body.removeChild(f)}
function setEndOfContenteditable(b){if(document.createRange){var f=document.createRange();f.selectNodeContents(b);f.collapse(!1);b=window.getSelection();b.removeAllRanges();b.addRange(f)}else document.selection&&(f=document.body.createTextRange(),f.moveToElementText(b),f.collapse(!1),f.select())}
function setJSSelect(b,f,g){console.log(b);b=b.value;console.log(b);var h=document.createElement("form"),p=document.createElement("input");p.setAttribute("type","hidden");p.name=g;p.value=b;h.method="POST";h.action=f;h.appendChild(p);document.body.appendChild(h);h.submit()}
function getDivContent(b,f,g){fdiv=document.getElementById(f).innerHTML;sdiv=document.getElementById(b).innerHTML;if(0<fdiv.trim().length){ndata=$j(fdiv).find(".removeti");console.log(ndata);for(b=0;b<ndata.length;b++){console.log(ndata[b]);var h="#"+$j(ndata[b]).attr("id");console.log(h);$j(h).remove()}fdiv=document.getElementById(f).innerHTML;console.log(fdiv);document.getElementById(g).value='<div class="jimgcont">'+fdiv.trim()+"</div>"}document.getElementById(g).value+=sdiv}
$j(document).ready(function(){function b(){var a=document.querySelectorAll(".arrow-wrapper"),c=document.querySelectorAll(".messenger-container"),e=document.querySelectorAll(".arrow-svg");document.querySelectorAll(".footer-container");var d=document.querySelectorAll(".to-who-wrapper"),n=document.querySelectorAll(".vestlusjutt");if(null!=a){$j(document).off("click",".arrow-wrapper");$j(document).on("click",".arrow-wrapper",function(a){console.log($j(this).offsetParent());var c=$j(this).offsetParent();
a=c.find(".messenger-container");c.find(".arrow-svg");c=c.find(".vestlusjutt");console.log(a);"grid"==$j(a).css("display")?$j(a).css("display","none"):($j(a).css("display","grid"),$j(c).scrollTop($j(c)[0].scrollHeight))});for(var b={$jscomp$loop$prop$i$10:0};b.$jscomp$loop$prop$i$10<a.length;b={$jscomp$loop$prop$i$10:b.$jscomp$loop$prop$i$10},b.$jscomp$loop$prop$i$10++)a[b.$jscomp$loop$prop$i$10].addEventListener("click",function(a){return function(){"grid"==c[a.$jscomp$loop$prop$i$10].style.display?
e[a.$jscomp$loop$prop$i$10].classList.remove("rotated"):(e[a.$jscomp$loop$prop$i$10].classList.add("rotated"),$j(n[a.$jscomp$loop$prop$i$10]).scrollTop($j(n[a.$jscomp$loop$prop$i$10])[0].scrollHeight),console.log($j(n[a.$jscomp$loop$prop$i$10])[0].scrollHeight));var b=d[a.$jscomp$loop$prop$i$10].querySelectorAll(".person-wrapper");b=$jscomp.makeIterator(b);for(var k=b.next();!k.done;k=b.next())card=k.value,card.classList.toggle("opened-grid-container")}}(b))}var k=document.querySelector(".huserlist");
null==k?console.log("null"):document.addEventListener("click",function(a){a.target.closest(".huserlist")||a.target.matches(".hideit")||k.classList.add("hideit")});a=document.querySelector(".open-filter-container");var t=document.querySelector(".filter-options");console.log(a);null==a?console.log("null"):(document.removeEventListener("click",x,!0),document.addEventListener("click",function(a){a.target.closest(".open-filter-container")?t.classList.toggle("open-filtering"):a.target.closest(".open-filtering")||
t.classList.remove("open-filtering")},!1))}function f(a){$j(this).removeClass("fupl-over");console.log(a);console.log(a.target.offsetParent);var c="";if("undefined"!=typeof $j(a.target).attr("data-id"))c=$j(a.target).attr("data-id");else if("undefined"!=typeof $j(a.target.offsetParent).attr("data-id")&&""==c)c=$j(a.target.offsetParent).attr("data-id");else if("undefined"!=typeof $j(a.target.parentElement).attr("data-id")&&""==c)c=$j(a.target.parentElement).attr("data-id");else if("undefined"==typeof c||
""==c)c=$j($j(a.target).closest("[data-id]")).attr("data-id");var e="";if("undefined"!=typeof $j(a.target).attr("data-pid"))e=$j(a.target).attr("data-pid");else if("undefined"!=typeof $j(a.target.offsetParent).attr("data-pid")&&""==e)e=$j(a.target.offsetParent).attr("data-pid");else if("undefined"!=typeof $j(a.target.parentElement).attr("data-pid")&&""==e)e=$j(a.target.parentElement).attr("data-pid");else if("undefined"==typeof e||""==e)e=$j($j(a.target).closest("[data-pid]")).attr("data-pid");var d=
"";if("undefined"!=typeof $j(a.target).attr("data-type"))d=$j(a.target).attr("data-type");else if("undefined"!=typeof $j(a.target.offsetParent).attr("data-type")&&""==d)d=$j(a.target.offsetParent).attr("data-type");else if("undefined"!=typeof $j(a.target.parentElement).attr("data-type")&&""==d)d=$j(a.target.parentElement).attr("data-type");else if("undefined"==typeof d||""==d)d=$j($j(a.target).closest("[data-type]")).attr("data-type");console.log($j(a.target).closest("[data-id]"));console.log($j(a.target).closest("[data-type]"));
console.log(typeof d);console.log(d);var n=!1;console.log(a.target.files);var b={type:d,progress:"progress"+c,id:c,pid:e};if("undefined"!=typeof a.target.files)for(e=0;e<a.target.files.length;e++)d=a.target.files[e],console.log(d),n=!0,d={"upfiles[]":d},D("",b,d,function(a,d,e){console.log(a);console.log(d.responseText);a=JSON.parse(d.responseText);console.log(a);$j("#imgdiv"+c).prepend(a.backto)});else if("undefined"!==typeof(a.dataTransfer||a.originalEvent.dataTransfer))a.preventDefault(),a.stopPropagation(),
e=(a.dataTransfer||a.originalEvent.dataTransfer).files,console.log(e),$j.each(e,function(a,d){console.log(a);console.log(d);console.log(d.type);if(-1!=d.type.indexOf("image")||-1!=d.type.indexOf("pdf"))n=!0,D("",b,{"upfiles[]":d},function(a,d,e){console.log(a);console.log(d.responseText);a=JSON.parse(d.responseText);console.log(a);$j("#imgdiv"+c).prepend(a.backto)})});else for(a=(a.clipboardData||a.originalEvent.clipboardData).items,console.log(a),e=0;e<a.length;e++){d=a[e];console.log(d.type);console.log(d.kind);
if(-1!=d.type.indexOf("text")||"string"==d.kind)return!0;if(-1!=d.type.indexOf("image")||"file"==d.kind){d=d.getAsFile();console.log(d);n=!0;d={"upfiles[]":d};for(var k=$jscomp.makeIterator(Object.entries(b)),t=k.next();!t.done;t=k.next()){var l=$jscomp.makeIterator(t.value);t=l.next().value;l=l.next().value;console.log(t+","+l)}D("",b,d,function(a,d,e){console.log(a);a=$jscomp.makeIterator(a.entries());for(e=a.next();!e.done;e=a.next());console.log(d.responseText);d=JSON.parse(d.responseText);console.log(d);
$j("#imgdiv"+c).prepend(d.backto)})}}1==n&&console.log("isFILE!");return!1}function g(){$j("#selectAll").change(function(){$j(".checkbox").prop("checked",$j(this).prop("checked"))});$j(".checkbox").change(function(){0==$j(this).prop("checked")&&$j("#selectAll").prop("checked",!1);$j(".checkbox:checked").length==$j(".checkbox").length&&$j("#selectAll").prop("checked",!0)});$j(".selectAllByType").change(function(a){if("undefined"!=typeof $j(this).attr("data-checktype")){var c=$j(this);a=$j(this).attr("data-checktype");
console.log(a);$j('[data-checktype="'+a+'"]').each(function(a,d){console.log($j(d).prop("checked"));$j(d).prop("checked",$j(c).prop("checked"))})}});$j("[data-checktype]:not(.selectAllByType)").change(function(a){console.log($j(this));$j(this);a=$j(this).attr("data-checktype");console.log(a);console.log($j('.selectAllByType[data-checktype="'+a+'"]'));0==$j(this).prop("checked")&&$j('.selectAllByType[data-checktype="'+a+'"]').prop("checked",!1);$j('[data-checktype="'+a+'"]:not(.selectAllByType):checked').length==
$j('[data-checktype="'+a+'"]:not(.selectAllByType)').length&&$j('.selectAllByType[data-checktype="'+a+'"]').prop("checked",!0)})}function h(){$j("select[data-getdt]").on("change",function(){console.log(this.value);if("string"==jQuery.type($j(this).attr("data-getdt"))){var a=E+$j(this).attr("data-getdt"),c=$j(this).attr("data-getnr");"undefined"==typeof c&&(c=0);var e=$j(this).attr("data-dsend");param={};param[e]=this.value;param.getnr=c;param.dget=$j(this).attr("data-dget");param.mopt=$j(this).attr("data-mopt");
console.log(param);var d=$j(this);$j.get(a,{param:param},function(a){A(a,d)})}});$j(".mepointwhat").on("change",function(){console.log(this.value);if(0<this.value)var a=$j(this).parent().find(".hideit");else 0>this.value&&(a=$j(this).parent().find(".showtemp"));$j.each(a,function(a){$j(this).is(":hidden")?($j(this).addClass("showtemp").removeClass("hideit"),console.log($j(this))):$j(this).addClass("hideit").removeClass("showtemp")})});$j("#regnewy").on("change",function(){var a=$j(this).parent().parent().parent().find(".hideit");
a.addClass("showtemp").removeClass("hideit");console.log(a)});$j("#regnewn").on("change",function(){var a=$j(this).parent().parent().parent().find(".showtemp");a.addClass("hideit").removeClass("showtemp");console.log(a)})}function p(){var a=document.querySelectorAll("input[type=date][data-dated]"),c=function(){var a=this.getAttribute("data-dated"),c=JSON.parse(a);a=document.getElementById(c.id);c=c.att;this.value&&a.setAttribute(c,this.value)};Array.from(a).forEach(function(a){a.addEventListener("change",
c)})}function m(){function a(a){c=!0;console.log(a);console.log(a.children());a.children().each(function(d,e){"string"==typeof $j(e)[0].id&&""!=$j(e)[0].id&&(d="#"+$j(e)[0].id,$j(d).on("mouseout",function(){c=!0;$j(a).data("closeit",!0)}));d=""});return c}var c=!0,e="";$j(document).off("change",'input[data-datalist="true"]');$j(document).on("change",'input[data-datalist="true"]',function(a){console.log($j(this).data("datalisto"));console.log($j(this).parent().find("#"+$j(this).data("datalisto")).attr("name"));
a=$j("#"+$j(this).attr("list")+' option[value="'+$j(this).val()+'"]');$j(this).parent().find("#"+$j(this).data("datalisto")).val(a.data("datalistid"));a=a.attr("data-addon");console.log(a);if("undefined"!=typeof a&&null!=a){a=JSON.parse(a);for(var c in a)console.log(c+": "+a[c].id+" "+a[c].value),$j("#"+a[c].id).val(a[c].value)}});$j(".udhover").on("click",function(a){var c=$j(this);a=c.closest("form");console.log(c.attr("data-uid"));console.log(c.attr("data-uname"));console.log(c.attr("data-src"));
console.log(c.attr("data-index"));console.log($j(a).data("strindex"));console.log(c.parent().parent().addClass("hideit"));console.log(a.find(".jutudivtags").html());var d=parseInt(c.attr("data-index")),e=c.attr("data-src"),b=c.attr("data-uname");c=c.attr("data-uid");var l=a.find(".jutudivtags").html();console.log(l);console.log(a.find(".jutudivtags").text());0<l.trim().length&&0<=d&&(a.find(".jutudivtags").focus(),a.find(".jutudivtags").html(replaceAt(l,d,e,'<span class="tagname" data-uid="'+c+'" data-tag="none">'+
b+"</span>&nbsp; ")),setEndOfContenteditable(a.find(".jutudivtags")[0]));console.log(a)});$j(".jutudivtags").off("focus");$j(".jutudivtags").on("focus",function(c){var d=$j(this).attr("data-jutuid"),b=$j(this).closest("form");$j(this).off("input");$j(this).on("input",function(c){var n=$j(this).html();c=n.indexOf("@");if(0<=c){$j(b).data("strindex",c);e=c;n=n.substring(c+1);var k=n.indexOf("&nbsp;");"undefined"==k&&(k=n.indexOf(" "));console.log(c+" "+k);k=n.substr(0,k);console.log(n);2<n.length&&
$j.get("get-utags.php",{js:"1",jutuid:d,user:n,user2:k,index:c},function(c){0<c.trim().length&&(console.log(b),a(b),$j("#huserlist"+d).html(""),$j("#huserlist"+d).html(c.trim()),$j("#huserlist"+d).removeClass("hideit"),m())})}else $j("#huserlist"+d).html(""),$j("#huserlist"+d).addClass("hideit")});$j(".jutudivtags").on("keydown",function(a){9==(a.keyCode||a.which)&&""!=e&&(a=$j(this).closest("form"),a=$j(a).find(".huserlist"),console.log(a),console.log(a.attr("id")),console.log($j("#"+a.attr("id")).find("a")[0]),
$j("#"+a.attr("id")).find("a")[0].focus())})});$j(".jutudivtags").on("focusout",function(a){$j(this).closest("form");console.log(c)})}function r(){var a=document.querySelector("input[data-searchwhere]");"undefined"!=typeof a&&null!=a&&a.addEventListener("change",function(c){c.preventDefault();c.stopPropagation();var e=document.querySelectorAll("."+a.dataset.searchwhere);e=Array.from(e).filter(function(d){if(d.id.replace(/\d+/g,"")==a.dataset.searchid)return d.textContent.toLowerCase().includes(c.target.value.toLowerCase())}).map(function(c){return c.id.substring(a.dataset.searchid.length)});
for(var d=document.querySelectorAll("."+a.dataset.searchwhat),b=0,f=d.length;b<f;b++)e.find(function(c){return c==d[b].id.substr(a.dataset.searchshide.length)})?document.getElementById(a.dataset.searchshide+d[b].id.substr(a.dataset.searchshide.length)).style.display="block":document.getElementById(a.dataset.searchshide+d[b].id.substr(a.dataset.searchshide.length)).style.display="none"})}function I(){var a=window.innerWidth,c=window.innerHeight;if("undefined"==typeof a||"undefined"==typeof c)a=window.outerWidth,
c=window.outerHeight;if("undefined"==typeof a||"undefined"==typeof c)a=screen.width,c=screen.height;c=Math.round(.98*c);$j("#resolwidth").val(a);$j("#resolheight").val(c);$j("#menudiv").attr("style","--height: "+c+"px")}function F(){var a=new Date;$j("#errchkdtime").html(a.toString());var c=$j("#errhash");if("undefined"!=typeof c){var e=c.html();if(0<c.length){c=parseInt($j("#errtim").html());timeoutnr="number"==typeof c?6E4*c:1E3;var d=window.location.href;console.log("This url: "+d);var b=$j("#errchkf").html();
"undefined"==typeof b&&(b="erhs.php");console.log("setTimeout is a GO!");clearTimeout(G);G=setTimeout(function(){$j.get(b,{erhas:e.trim()},function(c){$j("#errchkdtime").html(a.toString());1==parseInt(c.trim())?$j.get(d,{js:"1"},function(a){$j(baseto).hide();$j(baseto).html("");$j(baseto).fadeIn(150);$j(baseto).html(y(basefrom,a.trim()));F()}):F()});console.log("setTimeout is a GO, AGAIN!!")},timeoutnr)}else console.log("clearTimeout is a GO!"),clearTimeout(G)}}function S(){var a=$j(".copyclip");
if("undefined"!=typeof a&&0<a.length)$j(a).on("click",function(){var a=$j(this).parent().find(".urltocw");console.log(a);a.select();document.execCommand("copy")})}function u(a){a+="=";for(var c=document.cookie.split(";"),e=0;e<c.length;e++){for(var d=c[e];" "==d.charAt(0);)d=d.substring(1);if(0==d.indexOf(a))return d.substring(a.length,d.length)}return""}function y(a,c,e){if(""!=a){var d=$j($j.parseHTML(c)).find(a).html();parser=new DOMParser;doc=parser.parseFromString(c,"text/html");var b=doc.getElementsByTagName(a)[0];
if("undefined"!=typeof b)if("head"==a){d=b.getElementsByTagName("style");if("undefined"!=typeof b.getElementsByTagName("style")[0]){if("undefined"!=typeof b.getElementsByTagName("style")[0].outerHTML)var f="";for(var k in d)"undefined"!=typeof b.getElementsByTagName("style")[k].outerHTML&&(f+="\n"+b.getElementsByTagName("style")[k].outerHTML)}d=f}else d=b.innerHTML;"undefined"==typeof d&&(d=$j($j.parseHTML(c)).filter(a).html());"undefined"==typeof d&&(d=$j($j.parseHTML(c)).filter("#"+a).html());"undefined"==
typeof d&&(d=$j($j.parseHTML(c)).filter("."+a).html());"undefined"==typeof d&&(d=$j($j.parseHTML(c)).find("#"+a).html());"undefined"==typeof d&&(d=$j($j.parseHTML(c)).find("."+a).html());1==e&&("undefined"==typeof d&&(d=$j($j.parseHTML(c)).find(basefrom).html()),"undefined"==typeof d&&(d=$j($j.parseHTML(c)).filter(basefrom).html()));return"undefined"==typeof d?(a=c.indexOf("html"),e=c.indexOf("body"),-1==a&&-1==e?c:" "):d}"undefined"==typeof d&&(d=$j($j.parseHTML(c)).find(basefrom).html());"undefined"==
typeof d&&(d=$j($j.parseHTML(c)).filter(basefrom).html());return"undefined"==typeof d?" ":d}function B(a,c){var e="";"string"==jQuery.type(a.attr(c))?(a=a.attr(c).split(" "),c=a.length,1<c?(e=0==a[1].localeCompare("class")||0==a[0].localeCompare("class")?".":"#",3>c&&(a[0]=a[0].replace("id",""),a[0]=a[0].replace("class","")),e=a[0]+e+a[c-1]):e=1<=$j("#"+a).length?"#"+a:1<=$j("."+a).length?"."+a:a):""!=baseto&&"data-to"==c?e=baseto:""!=basefrom&&"data-from"==c&&(e=basefrom);return e}function A(a,c,
e){e=void 0===e?!0:e;console.log($j(this));console.log(c);var d=a.match(/console.log\(".*"\);/g);"undefined"!=typeof d&&""!=d&&(d=String(d).match(/"(.*)"/g),console.log(String(d).replace(/"/g,"").replace(/\\n/g,"\n")));d=c.attr("data-tfmulti");console.log(d);if("string"==typeof c.attr("data-to")||"string"!=typeof d)var b=B(c,"data-to");if("string"==typeof c.attr("data-from")||"string"!=typeof d)var f=B(c,"data-from");c=[];if("string"==typeof d){d.trim();var k=d.split(" "),t=k.length;if(1<t)for(d=
0;d<t;d++){if("undefined"!=typeof k[d]&&""!=k[d]){var l=k[d].replace("]","").split("[");c[l[0]]=1<l.length?l[1]:l[0]}}else 1==t?"undefined"!=typeof k[0]&&""!=k[0]&&(l=k[0].replace("]","").split("["),c[l[0]]=1<l.length?l[1]:l[0]):"undefined"!=typeof d&&""!=d&&(l=d.replace("]","").split("["),1<l.length?c[l[0]]=l[1]:c[d]=d)}"undefined"!=typeof c[b]&&""!=c[b]||"undefined"==typeof f||""==f||"undefined"==typeof b||""==b||(c[b]=f,console.log(c[b]+" def "+f+" "+b));console.log(c);console.log(u("extime")+
" <= "+Math.round((new Date).getTime()/1E3));parseInt(u("extime"))<=Math.round((new Date).getTime()/1E3)&&(c={body:"body"},console.log(u("extime")+" kypsis !! sec "+Math.round((new Date).getTime()/1E3)),console.log(c));for(var g in c)b=g,b=$j(b).length?b:$j("."+b).length?"."+b:"#"+b,console.log(b+" - "+c[g]),b=b.replace("<","").replace(">",""),c[g]=c[g].replace("<","").replace(">",""),"head"!=b&&($j(b).html(""),e&&$j(b).hide()),"head"==b?0==document.head.innerHTML.includes(y(c[g],a.trim()))&&a.includes("<"+
b+">")&&$j(b).append(y(c[g],a.trim())):(e&&$j(b).fadeTo(250,1),$j(b).html(y(c[g],a.trim())));return!0}function T(a){var c="";if("string"==jQuery.type(a.attr("data-to")))if(a=a.attr("data-to").split(" "),c=a.length,1<c){var b=a[1].localeCompare("class")||a[0].localeCompare("class")?"#":".";3>c&&(a[0]=a[0].replace("id",""),a[0]=a[0].replace("class",""));c=a[0]+b+a[c-1]}else c=1<=$j("#"+a).length?"#"+a:1<=$j("."+a).length?"."+a:a;""==c.trim()&&(c="#sisu");return c}function U(){0<$j("#reglog").length&&
V();if(0<$j("#newwin").length){T($j("#newwin"));var a=$j("#newwin").html();$j.get(a,{js:"1"},function(a){$j("#content",window.opener.document).hide();$j("#content",window.opener.document).html("");$j("#content",window.opener.document).fadeIn(350);$j("#content",window.opener.document).html(a.trim())});setTimeout("window.close()",1E3)}}function V(){$j("#SP_On").change(function(){$j("input[name=show_password]").is(":checked")?($j("#inputpassword").attr("type","text"),$j("#password").attr("type","text"),
$j("#password2").attr("type","text")):($j("#inputpassword").attr("type","password"),$j("#password").attr("type","password"),$j("#password2").attr("type","password"))})}function W(){$j(document).off("click","#removedisabled");$j(document).on("click","#removedisabled",function(a){var c=!0;a=$j("[data-disable]:disabled");0<a.length?c=!1:a=$j("[data-disable]");a.each(function(a){"undefined"!=jQuery.type($j(this).data("disable"))&&$j(this).prop("disabled",c)})});$j(document).off("click",".removedisabled");
$j(document).on("click",".removedisabled",function(a){if("string"==jQuery.type($j(this).attr("data-disableid"))){console.log($j(this).attr("data-disableid"));a=$j(this).attr("data-disableid");var c=!0,b=$j("[data-disabled='"+a+"']:disabled");0<b.length?c=!1:b=$j("[data-disabled='"+a+"']");console.log($j("[data-disabled='"+a+"']"));console.log($j("[data-disabled='"+a+"']"));b.each(function(a){"undefined"!=jQuery.type($j(this).data("disabled"))&&$j(this).prop("disabled",c)})}});$j(document).off("click",
"a");$j(document).on("click","a",function(a){console.log("a click ");console.log($j(this));if("string"==jQuery.type($j(this).attr("data-tab"))&&"true"==$j(this).attr("data-tab").substr(0,4)){var c=$j(this).attr("href");a=parseInt($j(this).attr("data-tabgroup"));var b=!1;"string"==jQuery.type($j(this).attr("data-tabparent"))&&"true"==$j(this).attr("data-tabparent").substr(0,4)&&(b=!0);if("string"==jQuery.type($j(this).attr("data-tabform"))){console.log("#"+$j(this).attr("data-tabform"));var d=$j("#"+
$j(this).attr("data-tabform")).find("*[required]");console.log(d);if("object"==typeof $j(d)){var n=!1;$j(d).each(function(a){console.log($j(this).val().length);0==$j(this).val().length||0==$j(this).val()?(console.log(a+": "+$j(this).val()),$j(this).addClass("redborder"),n=!0):$j(this).removeClass("redborder")});if(n)return!1}$j("<input>").attr({type:"hidden",id:"activetab",name:"activetab",value:c.split("#")[1]}).appendTo("#"+$j(this).attr("data-tabform"));$j("#"+$j(this).attr("data-tabform")).submit()}0<
a&&$j('[data-tabgroup="'+a+'"]').each(function(a,c){1==b&&$j(c).parent().removeClass("active");$j(c).removeClass("active")});1==b?$j(this).parent().addClass("active"):$j(this).addClass("active");$j("#"+c.split("#")[1]).addClass("active");return!1}if("string"==jQuery.type($j(this).attr("data-ignore"))&&"true"==$j(this).attr("data-ignore").substr(0,4))return!0;if("string"==jQuery.type($j(this).attr("data-confirm")))if(window.confirm($j(this).attr("data-confirm")))console.log("Confirm Yes");else return console.log("Confirm No"),
!1;if("string"==jQuery.type($j(this).attr("id"))){if("shownav"==$j(this).attr("id").substr(0,7)&&$j("#menurib").is(":hidden"))return $j("#menurib").show("slow","easeInOutQuart"),$j("#shownav").switchClass("shownav","shownav_clicked",1E3,"easeInOutQuad"),!1;if("shownav"==$j(this).attr("id").substr(0,7)&&$j("#menurib").is(":visible"))return $j("#menurib").hide("slow","easeInOutQuart"),$j("#shownav").switchClass("shownav_clicked","shownav",1E3,"easeInOutQuad"),setTimeout(function(){document.getElementById("menurib").style.display=
""},1E3),!1}if("string"==jQuery.type($j(this).attr("id"))&&"ui-id"==$j(this).attr("id").substr(0,5))return!1;c=$j(this).attr("href");if("_blank"==$j(this).attr("target"))return a="450",d="650","number"==jQuery.type($j(this).data("wwidth"))&&(a=$j(this).data("wwidth")),"number"==jQuery.type($j(this).data("wheight"))&&(d=$j(this).data("wheight")),console.log(d),window.open(c,"myWindow","width="+a+",height="+d+" "),!1;var f=$j(this).attr("id");a=B($j(this),"data-to");B($j(this),"data-from");"undefined"==
typeof $j("body").find(a).html()&&(a=baseto);if(""==c||"undefined"==typeof c)console.log("no url!");else{$j("body").removeClass("autopointer");$j("body").addClass("waitpointer");var k=this;$j.get(c,{js:"1"},function(a){if("string"==jQuery.type($j(k).attr("data-ignore"))){if("html"==$j(k).attr("data-ignore").substr(0,4)&&""!=$j(k).attr("data-dispnone"))return $j("#"+$j(k).attr("data-dispnone").trim()).css("display","none"),!1}else A(a,$j(k)),H(c);"langz"==f?J():K($j(k).attr("title"),c);x();$j("body").removeClass("waitpointer");
$j("body").addClass("autopointer")})}return!1})}function H(a){var c=a;console.log(a);if("object"==typeof a&&"string"==typeof a.href){c=a.href;c.trim();var b=c.split("#")}console.log(typeof b);"string"==typeof a&&"object"!=typeof b?(c.trim(),b=c.split("#")):b=[""];"undefined"==typeof b[1]&&u("scrollTo")&&u("scrollTo").length&&console.log(u("scrollTo"));if("undefined"==typeof b[1]){if("object"==typeof a){if(a.href.length)var d=new URL(a.href)}else console.log(a),console.log(a.search("https://")),d=
0<a.search("https://")?new URL(a):new URL("https://feik.org/"+a);"undefined"==typeof b[1]&&"string"==typeof d.searchParams.get("taskcode")&&(b[1]=d.searchParams.get("taskcode"),console.log(typeof b[1]),console.log(b[1]));"undefined"==typeof b[1]&&"string"==typeof d.searchParams.get("scrollTo")&&(b[1]=d.searchParams.get("scrollTo"),console.log(typeof b[1]),console.log(b[1]));null==b[1]&&"undefined"!=typeof a.href&&(b=a.href.split("#"),console.log(b[1]))}if("undefined"!=typeof b[1]&&null!=b[1]&&b[1].length&&
(console.log($j("#chk"+b[1]).prop("checked")),0==$j("#chk"+b[1]).prop("checked")&&$j("#chk"+b[1]).prop("checked",!0),console.log($j(2).toPx()),console.log(b[1]),console.log(typeof $j("#"+b[1])),"undefined"!=typeof $j("#"+b[1]).offset())){$j("html,body").animate({scrollTop:$j("#"+b[1]).offset().top-$j(6.5).toPx()},"slow");a=$j("#"+b[1]);c=1E3;b="";d="#33313e";if(void 0==c||""==c)c=200;if(void 0==b||""==b)b=$j(a).css("backgroundColor");void 0==d&&(d="#FFFF9C");$j(a).stop();L(a,1,d,b,c)}}function L(a,
c,b,d,n){0<c&&$j(a).animate({backgroundColor:b},n,function(){$j(a).animate({backgroundColor:d},n,function(){L(a,c-1,b,d,n)})})}function J(){for(var a=[],c=document.getElementsByTagName("span"),b=0;"undefined"!=typeof c[b];a.push(c[b++].getAttribute("data-tr")));c=document.getElementsByTagName("input");for(b=0;"undefined"!=typeof c[b];a.push(c[b++].getAttribute("data-tr")));c=document.getElementsByTagName("option");for(b=0;"undefined"!=typeof c[b];a.push(c[b++].getAttribute("data-tr")));c=document.getElementsByTagName("a");
for(b=0;"undefined"!=typeof c[b];a.push(c[b++].getAttribute("data-tr")));c=$j("base").attr("href");c+="gettext.php";console.log("url "+c);$j.post(c,{transl:a},function(a){$j.each(a.translations,function(a,c){console.log(a+" = "+c);var b=a.match(/%(\w+)%/gi);if(b){b=$jscomp.makeIterator(b);for(var d=b.next();!d.done;d=b.next()){d=d.value;d=d.toString();var e=$j("span[data-tr='"+a+"']").parent().attr("data-"+d.replace(/%/g,""));"undefined"==typeof e?e=$j("input[data-tr='"+a+"']").attr("data-"+d.replace(/%/g,
"")):"undefined"==typeof e&&(e=$j("*[data-tr='"+a+"']").attr("data-"+d.replace(/%/g,"")));c=c.replace(d,e)}}$j("span[data-tr='"+a+"']").html(c);$j("option[data-tr='"+a+"']").html(c);$j("input[data-tr='"+a+"'][placeholder]").attr("placeholder",c);$j("input[data-tr='"+a+"']").not("[placeholder]").val(c);$j("input[data-tr='"+a+"'][name=submit]").attr("value",c);$j("input[data-tr='"+a+"'][type=submit]").attr("value",c)})},"json")}function z(a,c,b){a.html("");a.html(c);a.removeClass("hideit");a.fadeIn("slow");
a.delay(1500);b&&a.fadeOut("slow",function(){$j(this).delay(500).addClass("hideit")})}function M(a,c){var b=new FileReader;b.onload=function(a){c.attr("src",a.target.result)};b.readAsDataURL(a)}function N(a,c){var b="undefined"!=typeof a.attr("data-action")?a.attr("data-action"):a.attr("action"),d=a.find("#uplist"),n=parseInt(a.find("#MAXUPL").val()),f=$j("#MAXNRU").val(),k=a.find("div[id^=upfilediv]").length;if(k>f)return!1;console.log(c);c="undefined"===typeof c[0].name?a.find("input[type=file]")[0].files:
c;console.log(b);0<n||(n=2097152);1<=c.length&&d.removeClass("hideit");for(d=0;d<c.length;d++){var g=c[d];console.log(k+". "+g.name);console.log(k+" <= "+f+" = "+parseInt($j("input[id^=numb]").last().attr("value")));(0<d||0<parseInt($j("input[id^=numb]").last().attr("value")))&&k<=f+1&&$j("div[id^=upfilediv]").last().clone().appendTo("#uplist:last");var l=a.find("div[id^=upfilediv]").length,h=$j("div[id^=upfilediv]").last();h.attr("id",function(){return"upfilediv["+l+"]"});h.find(".jartsnr").attr("id",
function(){return"jartsnr["+l+"]"});h.find("progress").attr("id",function(){return"progress["+l+"]"});h.find(".preimg").attr("id",function(){return"preimg["+l+"]"});h.find("input[type=number]").attr("id",function(){return"numb["+l+"]"});h.find(".errordiv").attr("id",function(){return"fuplerr["+l+"]"});var p=h.find("#jartsnr\\["+l+"\\]"),R=h.find("#progress\\["+l+"\\]"),m=h.find("#preimg\\["+l+"\\]"),r=h.find("#numb\\["+l+"\\]");r.attr("name","numb["+l+"]");h=h.find("#fuplerr\\["+l+"\\]");var q=!0,
v="";console.log(m);m.attr("data-nr",l);p.html(l);p.removeClass("hideit");r.attr("value",l);n<parseInt(g.size)&&(console.log("Too big!"),q=!1,v="Too big!");0!=g.type.indexOf("image")&&(console.log("Not image!"),q=!1,v="Not image!",m.addClass("hideit"),p.addClass("hideit"));k>f&&(q=!1,v="No more uploads left",m.addClass("hideit"),p.addClass("hideit"));q?(console.log("Faili saatmine "+q+" = "+b),M(g,m),m.removeClass("hideit"),X(b,g,k,R,m),k++):(z(h,v,!1),console.log("Faili saatmine, ERROR: "+v));k>=
f&&(console.log(f+" >= "+k),a.find("#myupl").fadeOut("slow",function(){$j(this).delay(500).addClass("hideit")}))}}function X(a,c,b,d,n){var e=new XMLHttpRequest,f=new FormData;e.open("POST",a,!0);e.upload.onprogress=function(a){a=Math.ceil(a.loaded/a.total*100);d.removeClass("hideit");d.attr("value",a)};e.onreadystatechange=function(a){if(4==e.readyState&&200==e.status){d.addClass("hideit");n.removeClass("hideit");M(c,n);console.log("Done!");console.log(e.responseText);if("undefined"!=typeof e.responseText){var b=
JSON.parse(e.responseText);n.attr("data-funame",b.fname)}console.log(b.fdebug)}};f.append("uploadednr",b);f.append("fup","true");f.append("myfile["+b+"]",c);e.send(f)}function O(a,c,b){var d=["image/gif","image/jpeg","image/png"],e="undefined"===typeof b?a.find("input[type=file]")[0].files[0]:b[0];console.log(e);a.find("input[type=file]").val("");if("string"!=typeof e.name&&"File"!=e.__proto__.constructor.name)return!0;var f=parseInt(a.find(".MAXUPL").val());0<f||(f=2097152);var k="undefined"!=typeof a.attr("data-action")?
a.attr("data-action"):a.attr("action"),g=parseInt(e.size),l=a.find(".preimg"),h=a.find("progress");a.find(".somebutton");var p=$j(".picreq");if("undefined"===typeof h[0]){var m=$j(".kkkpickes").find(".progress");console.log(m);"undefined"==typeof m[0]&&(m=$j("#kkkpickes").find(".progress"));console.log(m);"undefined"==typeof m[0]&&(m=a.find(".progress"));l=h=m.find("progress");console.log(m)}console.log(h);console.log(m);var r=a.find("#delpic"),u=a.find(".errordiv"),q=new XMLHttpRequest;b=new FormData;
console.log(l);l.hasClass("hideit");console.log("edasi");var v=$j(".errormessage");if(0!=e.type.indexOf("image")||0>$j.inArray(e.type,d))return z(u,"Not image!"),console.log("Not image!"),"undefined"!=typeof v[0]&&(z(v,"Not image!"),console.log("Not image!")),!1;if(f<g)return z(u,"Too big!"),console.log("Too big!"),!1;console.log(k);q.open("POST",k,!0);q.upload.onprogress=function(a){a=Math.ceil(a.loaded/a.total*100);h.removeClass("hideit");h.attr("value",a)};console.log(r);q.onreadystatechange=function(a){if(4==
q.readyState&&200==q.status){0==e.type.indexOf("image")&&(a=new FileReader,a.onload=function(a){l.removeClass("hideit");h.addClass("hideit");r.removeClass("hideit");l.attr("src",a.target.result);p.attr("value","1");console.log("done!");z(v,"&nbsp;",!0)},a.readAsDataURL(e));if("undefined"!=typeof q.responseText){console.log(q.responseText);a=JSON.parse(q.responseText);"undefined"==typeof m&&"undefined"!=typeof h&&(m=h);var c;"undefined"==typeof c&&"undefined"!=typeof m[0]&&(c=$j(m[0].parentNode.offsetParent).find("tr").first());
if("undefined"==typeof c||"undefined"==typeof c[0])c=m.parent().find("li").first();console.log(c);$j(a.addon).insertAfter(c)}console.log("UpTo "+k+" Done!")}};console.log(a);finputs=a[0].getElementsByTagName("input");console.log(finputs);a=0;for(d=finputs.length;a<d;a++)"hidden"===finputs[a].type&&""!=finputs[a].name&&(b.append(finputs[a].name,finputs[a].value),console.log(finputs[a].name+" - "+finputs[a].value));b.append("myfile["+c+"]",e);q.send(b)}function D(a,c,b,d){var e=new XMLHttpRequest,f=
new FormData;""==a&&(E=$j("base").attr("href"),a=E+"mapi.php");e.open("POST",a,!0);e.upload.onprogress=function(a){console.log(a);"undefined"!=typeof c.progress&&console.log(Math.ceil(a.loaded/a.total*100))};e.onreadystatechange=function(c){4==e.readyState&&200==e.status&&(console.log("Done!"+a),console.log(e.responseText),"undefined"!=typeof e.responseText&&"function"===typeof d&&d(f,e,c))};if("object"===typeof c)for(var g=$jscomp.makeIterator(Object.entries(c)),h=g.next();!h.done;h=g.next()){var l=
$jscomp.makeIterator(h.value);h=l.next().value;l=l.next().value;f.append("options["+h+"]",l)}else f.append("options",c);if("object"===typeof b)for(b=$jscomp.makeIterator(Object.entries(b)),g=b.next();!g.done;g=b.next())h=$jscomp.makeIterator(g.value),g=h.next().value,h=h.next().value,f.append(g,h);else f.append("addata",b);e.send(f);console.log(e);return e}function Y(){(function(){var a=document.createElement("div");return("draggable"in a||"ondragstart"in a&&"ondrop"in a)&&"FormData"in window&&"FileReader"in
window})()&&($j(".myupl").addClass("has-advanced-upload"),$j(".dragdroptext").removeClass("hideit"),$j(".picsubmit").addClass("hideit"));$j(".ui-sortable").sortable({handle:".sortimg",placeholder:"placeholder",start:function(a,c){$j(c)[0].item.find(".drgimg img").attr("src","img/drag_on.png")},stop:function(a,c){$j(c)[0].item.find(".drgimg img").attr("src","img/drag_off.png");var b=$j(c)[0].item.parent().find(".masterjrk");console.log(c);if(1>b.length){b=$j(this).find(".drgjrk");if(1<=b.length){jarknr=
"undefined"!=typeof $j("input[name='jarknr']").val()?parseInt($j("input[name='jarknr']").val()):1;if("number"!=typeof jarknr||0>=jarknr)jarknr=1;for(var d in b)if(b.hasOwnProperty(d)){var f=$j(b[d]);a=f.data("ktid");console.log("jrkid:"+a);console.log(parseInt(d)+jarknr);f=parseInt(d)+jarknr;$j("#ktjrkspan_"+a).html(f+".");$j("#ktjrk_"+a).val(f)}}console.log($j($j(c)[0].item[0].previousElementSibling).find(".kttsamaa option:selected").val());d=$j($j(c)[0].item[0].previousElementSibling).find(".kttsamaa option:selected").val();
"undefined"==typeof d&&(d=$j($j(c)[0].item[0].nextElementSibling).find(".kttsamaa option:selected").val(),"undefined"==typeof d&&(d=0));$j($j(c)[0].item.find(".kttsamaa")).val(d)}else if(1<=b.length)for(d in jarknr=1,b)b.hasOwnProperty(d)&&(f=$j(b[d]),a=f.data("mjrkid"),console.log(f),console.log(a),f=parseInt(d)+jarknr,$j("#mjrk"+a).html(f+"."),$j("#mnjrk"+a).val(f))}});$j(document).off("drag dragstart dragend dragover dragenter dragleave drop",".myupl");$j(document).on("drag dragstart dragend dragover dragenter dragleave drop",
".myupl",function(a){console.log("Dr\u00e4\u00e4\u00e4g ");a.preventDefault();a.stopPropagation()});$j(document).on("dragover dragenter",".myupl",function(){$j(this).addClass("is-dragover")});$j(document).on("dragleave dragend drop",".myupl",function(){$j(this).removeClass("is-dragover")});$j(document).on("drop",".myupl",function(a){a.stopPropagation();a.preventDefault();console.log("Dropp, babammm ");var c=$j(this).parents("form"),b=a.originalEvent.dataTransfer.files;console.log(c);var d=$j(c).find("#myfile");
"undefined"!=typeof d.attr("multiple")?(console.log("change "+d.attr("multiple")+" "+typeof d.attr("multiple")+" "+d.attr("name")),N(c,b)):O(c,1,b);a.originalEvent.dataTransfer.clearData();console.log("Dropp, babammm l\u00f6pp")});$j(function(a){a=$j("base").attr("href");console.log("f-I-e "+a);$j($j(this).find("input[data-confirm]")).off("click");$j($j(this).find("input[data-confirm]")).click(function(){if("string"==jQuery.type($j(this).attr("data-confirm")))if(window.confirm($j(this).attr("data-confirm")))console.log("Confirm Yes");
else return console.log("Confirm No"),!1})});$j(document).off("focus","input[data-autocomplete]").on("focus","input[data-autocomplete]",function(a){var c=this;a=$j("base").attr("href");if("string"==jQuery.type($j(c).attr("data-getdt")))var b=a+$j(c).attr("data-getdt");console.log("data-autocomplete");var d="string"==jQuery.type($j(c).attr("data-autocomplete"))?$j(c).attr("data-autocomplete"):"autocomplete";if("string"==jQuery.type($j(c).attr("data-extradata")))var f=$j(c).attr("data-extradata");"string"==
jQuery.type(b)&&(console.log(b),$j(this).autocomplete({delay:250,minLength:3,source:function(a,c){console.log(b+"!!");var e={};$j.ajax({url:b,dataType:"json",data:(e[d]=a.term,e.extradata=f,e),success:function(a){console.log("data:");console.log(a);c(a)}})},select:function(a,b){console.log("Selected: "+b.item.value+" aka "+b.item.id);"string"==jQuery.type($j(c).attr("data-tfmulti"))&&(a="<div id="+$j(c).attr("data-tfmulti")+">Selected: "+b.item.value+" id "+b.item.id+"</div>",A(a,$j(c)));a="string"==
jQuery.type($j(c).attr("data-inpname"))?$j(c).attr("data-inpname"):$j(c).attr("name")+"_id";$j(c).append("<input type='hidden' name='"+a+"' value='"+b.item.id+"'>")}}))});if("string"==jQuery.type($j("form").attr("data-ignore"))&&"true"==$j("form").attr("data-ignore").substr(0,4))return!0;$j("form").ajaxForm({data:{js:1},beforeSubmit:function(a,c,b){b=$j(c).find("#kkkkystext");if("undefined"!=typeof b[0])for(var d=$j(c).find(".button"),e=0;e<d.length;e++)$j(d[e]).hide();var f;a.forEach(function(a){"submit"==
a.type&&"ignore"==a.name&&(console.log(this),f=!0)});if("undefined"!=typeof f&&f)return!0;a=$j(c).find(".valstartdate");e=$j(c).find(".valestdate");var g=$j(c).find(".errormessage"),h=new Date(a.val()),l=new Date(e.val());c=$j(c).find(".required");console.log(c);if("undefined"!=typeof c[0]&&(console.log(c.val()),1!=c.val()&&"undefined"!=c.val())){g.html("Error: "+c.val());if("undefined"!=typeof b[0])for(e=0;e<d.length;e++)$j(d[e]).show();return!1}if(h>l)return g.html("Error: "+a.val()+" > "+e.val()),
!1;$j("body").removeClass("autopointer");$j("body").addClass("waitpointer")},type:"post",success:function(a,c,b,d){console.log("ajaxForm");c=$j(d).formSerialize();b=$j(d).attr("action");"undefined"==typeof b&&(b=$j("base").attr("href"));var e=$j(d).attr("title");255>c.length&&K(e,b+"?"+c.replace(/(password=.*?(&|[^&]*))/gi,"").replace(/(password2=.*?(&|[^&]*))/gi,"").replace(/(myfile.*?(&|[^&]*))/gi,""));e=!0;"string"==jQuery.type($j(d).attr("data-fade"))&&"false"==$j(d).attr("data-fade").substr(0,
5)&&(e=!1);console.log("fade:"+e);A(a.trim(),d,e);console.log(b);console.log(b.search("#"));0>b.search("#")&&(b=b+"?"+c.replace(/(password=.*?(&|[^&]*))/gi,"").replace(/(password2=.*?(&|[^&]*))/gi,"").replace(/(myfile.*?(&|[^&]*))/gi,""));H(b);$j("body").removeClass("waitpointer");$j("body").addClass("autopointer");x();c.includes("lang")&&J()}});$j(document).on("click",".ignorebutton",function(a){$j($j($j(document).find(this)[0].form)).find("input, select, textarea").each(function(){$j(this).removeAttr("required");
$j(this).removeAttr("min")})});$j(document).off("submit","form");$j(document).on("submit","form",function(a){console.log("submit")});$j(document).off("change","form");$j(document).on("change","form",function(a){console.log("change");console.log(a);a=$j(this).find("input:file");var b=$j(this).find(".myupl");0!=a.length&&0<b.length&&("undefined"!=typeof a[0].files[0]||"undefined"!=typeof a.files||"undefined"!=typeof b[0].files)&&(console.log("change "+$j(this).attr("name")+" "+typeof b.attr("multiple")+
" "+b.attr("name")),"undefined"!=typeof b.attr("multiple")?(N($j(this),b[0].files),console.log("upFiles change")):(console.log(a),O($j(this),1,a[0].files),console.log("upFile Change")))})}function x(){$j("div[contenteditable]").keydown(function(a){if(13===a.keyCode)return document.execCommand("insertHTML",!1,"<br><br/>\n\r"),!1});Y();U();W();g();h();S();I();m();r();F();p();$j(".deleteimg").hover(function(){$j(this).attr("src",$j(this).data("delimgon"))},function(){$j(this).attr("src",$j(this).data("delimg"))});
$j(document.activeElement).off("paste");$j(document.activeElement).on("paste",f);$j(".vestlus, .jfup").off("dragover");$j(".vestlus, .jfup").on("dragover",function(a){a.preventDefault();a.stopPropagation();$j(this).addClass("fupl-over");return!1});$j(".vestlus, .jfup").off("drop dragend dragenter dragleave");$j(".vestlus, .jfup").on("drop dragend dragenter dragleave",function(a){$j(this).removeClass("fupl-over")});$j(".vestlus, .jfup").off("drop");$j(".vestlus, .jfup").on("drop",f);$j(".jfup").off("change");
$j(".jfup").on("change",f);for(var a=document.getElementsByClassName("vestlusjutt"),c=0;c<a.length;c++){var e=$j(a.item(c));$j(a.item(c)).scrollTop(e[0].scrollHeight);console.log($j(a.item(c)))}$j(".vestlusjutt").scroll(function(a){var b=$j(this);if($j(this).scrollTop()==$j(this).height()-$j(this).height()){var c=$j(this).attr("data-loader"),d=$j(this).attr("data-mdata")+".php";a=$j(this).attr("data-nom");var e=$j(this).attr("data-prui"),f="";"undefined"!=typeof $j(this).attr("data-type")&&(f=$j(this).attr("data-type"));
var g=$j(this).children().first().attr("data-countd");$j.ajax({url:d,type:"GET",data:{nr:a,sec:g,loaderid:c,prui:e,type:f},beforeSend:function(){$j("#loading"+c).show()},complete:function(){$j("#loading"+c).hide("slow")},success:function(a){b.prepend($j(a).hide().fadeIn("slow"));console.log(d);console.log(a);$j(b).scrollTop(4)},error:function(){}})}});b()}function K(a,b){b=b.replace(/(password=.*?(&|[^&]*))/gi,"");var c=b.indexOf("?"),d=b.indexOf("#");-1<c&&-1<d&&(console.log("? ja # olemas!"),d<
c&&(b=b.split("#"),c=b[1].split("?"),b=b[0]+"?"+c[1]+"#"+c[0]));console.log(b);"undefined"!=typeof history.pushState?(b={Page:a,Url:b},"undefined"!=typeof a?history.pushState(b,b.Page,b.Url):history.pushState(b,null,b.Url)):alert("Browser does not support HTML5.")}console.log(document.location);H(document.location);console.log(window.location);var E=(document.querySelector("base")||{}).href,w=(new Date).getTimezoneOffset(),P=Math.abs(w);w=(0>w?"+":"-")+("00"+Math.floor(P/60)).slice(-2)+":"+("00"+
P%60).slice(-2);document.cookie="hp_time_offset="+w+"; expires=Fri, 31 Dec 9999 23:59:59 GMT";I();var C=$j("#kkkstatn");"undefined"!=typeof C[0]&&C[0].checked&&(w=$j(C[0].form).find("#kkkstatp"),$j(w).on("change",function(a){C.prop("checked",!1)}));$j(document).on("click",".pluss",function(a){a.preventDefault();if("undefined"==typeof $j(this).data("adnrz"))if("undefined"!=typeof $j(this).data("adnr")){a="undefined"!=typeof $j(this).attr("data-style")?$j(this).attr("data-style"):"";$j("#"+$j(this).data("idt")).append('<div id="'+
$j(this).attr("data-id").replace(/[0-9]/g,"")+$j(this).attr("data-adnr")+'" class="'+a+'">'+$j("#"+$j(this).attr("data-id")).html()+"</div>");a=$j("#"+$j(this).attr("data-id").replace(/[0-9]/g,"")+$j(this).attr("data-adnr"));var b=a.find(".pluss");console.log($j(this).data("idt"));a.find(".miinus");b.attr("data-id",b.attr("data-id").replace(/[0-9]/g,"")+$j(this).data("adnr"));b.attr("data-adnr",parseInt($j(this).data("adnr"))+1);b.attr("id",b.attr("id").replace(/[0-9]/g,"")+$j(this).data("adnr"));
b=a.find("[data-getdt]");var e=a.find("input[type=date]");console.log(e);var d=b.attr("data-tfmulti"),f=b.attr("data-getnr"),g=b.attr("name"),k=e.attr("name");console.log(k);"undefined"!=typeof k&&e.attr("name",k.replace(f,parseInt($j(this).attr("data-adnr"))+1));"undefined"!=typeof g&&b.attr("name",g.replace(f,parseInt($j(this).data("adnr"))+1));b.attr("data-getnr",parseInt($j(this).data("adnr"))+1);"undefined"!=typeof d&&b.attr("data-tfmulti",d.replace(/[0-9]/g,"")+(parseInt($j(this).data("adnr"))+
1));a.find("#"+d).html("");"undefined"!=typeof d&&a.find("#"+d).attr("id",d.replace(/[0-9]/g,"")+(parseInt($j(this).data("adnr"))+1));0!=parseInt($j(this).attr("data-adnr"))?($j(this).attr("src",$j(this).attr("src").replace("pluss","minus")),$j(this).attr("class",$j(this).attr("class").replace("pluss","miinus"))):$j(this).remove()}else $j("#"+$j(this).data("idt")).append('<div id="'+$j(this).data("id")+'">'+$j("#"+$j(this).data("id")).html()+"</div>");h()});$j(document).on("click",".miinus",function(a){console.log($j(this).data("id"));
console.log("#"+$j(this).attr("data-id"));$j("#"+$j(this).attr("data-id")).find("input").val("");$j("#"+$j(this).attr("data-id")).find("select").val("");$j("#"+$j(this).attr("data-id")).addClass("hideit");$j("#"+$j(this).attr("data-id")).remove()});var G,Q="state"in window.history&&null!==window.history.state,Z=location.href;$j(window).bind("popstate",function(a){a=!Q&&location.href==Z;Q=!0;a||$j.get(location.href,{js:"1"},function(a){$j(baseto).hide();$j(baseto).html("");$j(baseto).fadeIn(350);$j(baseto).html(y(basefrom,
a.trim()));x()})});x()});$j.fn.toRem=function(b){b=jQuery.extend({scope:"body"},b);var f=parseInt(this[0],10);b=jQuery('<div style="display: none; font-size: 1rem; margin: 0; padding:0; height: auto; line-height: 1; border:0;">&nbsp;</div>').appendTo(b.scope);var g=b.height();b.remove();return(f/g).toFixed(8)};
$j.fn.toPx=function(b){b=jQuery.extend({scope:"body"},b);var f=parseFloat(this[0]);b=jQuery('<div style="display: none; font-size: 1rem; margin: 0; padding:0; height: auto; line-height: 1; border:0;">&nbsp;</div>').appendTo(b.scope);var g=b.height();b.remove();return Math.round(f*g)};
